sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: YbCy9vaf86vp6V/1/GACdXzhTH2XocJMjJjG8bc+X8cIC8E1c+M1/VA678kiASnUeI9AYgMEpE2xX1MaPhouCscCi+mhNIlesi/oRNdCSnjp1+dyWID2e2DqksOtuL9iKcJIs8s9epdHk/aeTGQz7k4TYJHKTxVeh5VBNlT4eJCf41hYAaRYDJj2iM2iT2iQ3HgxynO2GC5rOzJg7EnIuICTV4DdG+3Vk3JGgcNHww1uKZWOxBMSgT/94B42yVogB4qlTmza/Kuj7W/zldz5pxW1g9ccDoDJyulYNM297TiirtobEoFYnPOTYKwn7BSIsywqTlbsOfLOJ9iccMRUayhqr6m8BMWNyUDk4CXqgJJ1jvZ9Sr4DLen98e91B1VKSW1ntmFQ3fugsDPoXQ4V3vHrqvnN8+0LcA9akAGRqjimM7tnQA8hGhGHDIKScS3Z5hMvohJ8oNyD3h30JJabPf3ii6MRMjldba6P+0MICKK2lRXZ/yzwbArqsoMRrHmnEqUdEqZUEuw2VUPzQiVq6AZO64otiJdbSrR5L69Plra2IrqYxbMspqxkE4idEE+RwdIXxBWZtql06m7WrBfmvTFUAveZ4TvD+Af478bHT5cx14QcVUILe91NMw0fTtxfzvIk3bv1bKOjnuS5a6Lag0TuO8oUSD5VsctK4LP5qzg=
  - secure: V+oJnh4HnK6tR7N7HVoYo9AhNmFC1OO4EMaeTFqyEnaFpegxazeSz0aUJiIRKOAlO5NmqnACyKPCWfMaxYz83uV/GWCZqZ68qw/aWle2rHsRo+ZJt4Pv7f3sboiRDgHkV9orEqazzJOZ65U9L+ACi88oUR1jehWBDh4hu59AqAYLJnSgjnRdzlK+6doWKobPn0LyjGpQKjz3KbYduxnt8gQeDyEPkM80NeonDnmoPEB615hHKAVnWis7TeKp4bw1nSti25BNVVmIeK8g9J5Ll0aArg7Kc3WM5Rn8Xcz1b/VWTB0YDf+mXPfJBU6RpSXGKjCAv10nzvQjGQRrBO6cR79TM/WnXQh/ecmHF3vqRULKS4gwiB7sNURJ9Alnc3wixxH0eVBTLPiDglHHZjn12cdkBFNUDEgSKikPvb9VEZPV43Z6WI80wLBj22lQRPoaen3aPf+pdxcK+Hh5VUkRK0IcOpW5ln0gCxuqqduW2RBn4uV1J12p3adEAtudFMFhlzqnxS838y0CGvjx+IdSST+4pTdiZxE3QIIywmV0HilU6I9qJdcRBTcvnpoiPviLpj0fnsriPP7fMwrzcyM34QZQpGYPYU/z9d6caq+0jejRdOy7ibUHqQxOj3+MciRkYaKxZF5JT/4WvRnxwSXzFyF8KMHw9tNdcLo9j0WFqG0=
  - secure: YCzjWzslCcek6fauRx5+hWjITAq8R07RGgDYExIrL+toiFQ9VTK0ZjlG6litRHoH5tANQpqecNs/aNdUw7w37+Nak18O8Z61ArQ5XljB+mzA160zjAsv0tvrsxoUdlURJ2RIqlCLwB56+WmkWIUs4+S8siwwtxcM363uEQpnlSVKIqtwzqwhLTmGag9uvgUTnIasNMhfgC/CC4J60AYQ+zv/Vdt/KUvTvKd7qFBfA7xg+UGfsI5lhbYlameQUERUhuXzsQYbHwx0AppHIlWH/eV44ZWnfGt0ElOLVCUf6Iyv5VTA6MLcKCwM30XoVFKGml9U2xsHPhV4AOyGtlYUPzcuMXM+8fYSYATelLPK18ZMFIVYPRk2THsUmmSH443SDnqy0xEAg64mC+YLMTfAsrXNArAVDz6N7FqRWjCNkmHoj+uXvAQztHURPOm5MjPaOz30QG+54z0uwmTxNv//wX7PBzSvnIrzZ6YEL/Y071kYD6KVvEXXRcBHL+teUd9BaP3kTDeTt59lC9JUw6sXDMA1Wb83/WV4ao1IlTZuH0pzkF45KBAfRMomKu/N9b3HTQhLq7kTEYhmpRvARPf3jdF5iM1kwOof4pWge91VHgr7DErh5+yZXruAgfBLilEhzOc7RvPOlvRfYk+EExZcvCtchkTNZUBOUOj8mGnmJl0=
  - secure: ZExMrquWpt6n1COiKpmtSA1AhFU3WV1eEb16/H5km4tnsr57nldsFRVhHdwEeSFJanZA/uVm57kTL9IbB1ODg8w7wLeX0+YDQmDR2O7DQdSauIul9JBYoLKnfbDV2jKtopBugJFoxKoqG5jQQOqRMehWh1cXpd0g/D5IjaxgAaTU9Ssod/6BRQCoQj3pkzZobXNNdjQvDnzW2rZL887kPBZqm76O4fvwLDUSIAyLZBZ7vWkxQlXeBibmIakwC2scOAOwI0oGlsP/RMvV7pwi6fnrGDs6GGGYGAvaSW0tvMpHk1gmFjQQefZk8odFlsVgWC07vlz5g9XoZg4PaMTQu9VagrIIZbCYr1XTP+2kT1/v+ZGrBDYZ+d2yejsBiKryLFQnacjud69XAO6HrjFmS+tZaGVPtcHEwioODQ3tiqFmFDdkkKnbn4/L9ldFO3fHyu3wDSz1A1TKf+RlE9dpB5y4UguMzarcUhEdL8GuYKtWlBFiDBxXP95sCPfEbetapv8Yv0Da6WPyzbOUkfcLVP2SNs167digAOSI5d/Y020bJ9DeYyUQ3lQCLDe2A5FJlqFBAJxik5AuG4sqgplKwg4iG09AXwuLfKPgthKpc5xiMXcL/C8/ZaFdo5Y+gpjPqw9jPpzEZahq6WsNXr9MzMATJq28tWWyH2JwyH4A0ds=
